export type WorkspaceRole =
  | "operations_admin"
  | "triage_specialist"
  | "knowledge_manager";

export type WorkspaceUserStatus = "active" | "pending";
export type WorkspaceProviderStatus = "local" | "manual_required" | "planned";

export type WorkspaceStaffUser = {
  id: string;
  name: string;
  email: string;
  role: WorkspaceRole;
  status: WorkspaceUserStatus;
};

export type WorkspaceIntegrationStatus = {
  id: string;
  label: string;
  status: WorkspaceProviderStatus;
  summary: string;
  nextStep: string;
};

export type WorkspaceDomainEntity = {
  id: string;
  label: string;
  description: string;
};

export type WorkspaceManualWorkItem = {
  id: string;
  label: string;
  description: string;
};

export type WorkspaceWorkflowStage = {
  id: string;
  label: string;
  description: string;
};

export const workspaceRoleLabels: Record<WorkspaceRole, string> = {
  operations_admin: "Operations Admin",
  triage_specialist: "Triage Specialist",
  knowledge_manager: "Knowledge Manager",
};

export const workspaceStaffDirectory: WorkspaceStaffUser[] = [
  {
    id: "USR-1001",
    name: "Ava Patel",
    email: "ava.patel@edumailai.local",
    role: "triage_specialist",
    status: "active",
  },
  {
    id: "USR-1002",
    name: "Noah Kim",
    email: "noah.kim@edumailai.local",
    role: "operations_admin",
    status: "active",
  },
  {
    id: "USR-1003",
    name: "Priya Shah",
    email: "priya.shah@edumailai.local",
    role: "knowledge_manager",
    status: "active",
  },
  {
    id: "USR-1004",
    name: "Jordan Lee",
    email: "jordan.lee@edumailai.local",
    role: "triage_specialist",
    status: "active",
  },
];

export const workspaceIntegrationStatuses: WorkspaceIntegrationStatus[] = [
  {
    id: "database",
    label: "Database",
    status: "local",
    summary: "Mailbox, activity, and document metadata currently persist to local JSON files.",
    nextStep: "Choose a hosted or self-managed database and provide connection details.",
  },
  {
    id: "auth",
    label: "Authentication",
    status: "manual_required",
    summary: "No sign-in flow or roles are enforced yet.",
    nextStep: "Choose an auth provider and define role/permission rules.",
  },
  {
    id: "file-storage",
    label: "File Storage",
    status: "local",
    summary: "Knowledge documents are stored in the project workspace for local use.",
    nextStep: "Select production file storage for documents and long-term retention.",
  },
  {
    id: "ai-provider",
    label: "AI Draft Provider",
    status: "planned",
    summary: "Drafts are currently seeded/local and not generated by a live model.",
    nextStep: "Choose an AI provider and grounding strategy for live reply generation.",
  },
  {
    id: "email-inbox",
    label: "Inbox Integration",
    status: "manual_required",
    summary: "Messages are local demo cases and are not synced from a real helpdesk or mailbox.",
    nextStep: "Choose an inbound email/helpdesk provider and define sync rules.",
  },
  {
    id: "hosting",
    label: "Hosting and Observability",
    status: "manual_required",
    summary: "The prototype is local-only and has no deployment or monitoring configuration.",
    nextStep: "Choose a hosting platform and basic monitoring stack before launch.",
  },
];

export const workspaceFutureDomainModel: WorkspaceDomainEntity[] = [
  {
    id: "users",
    label: "Users and Roles",
    description: "Staff identity, role assignment, approval permissions, and ownership rules.",
  },
  {
    id: "messages",
    label: "Messages",
    description: "Inbound emails, routing state, reply drafts, and review outcomes.",
  },
  {
    id: "ownership",
    label: "Ownership and Notes",
    description: "Case ownership, internal notes, escalation reasons, and last-updated timestamps.",
  },
  {
    id: "documents",
    label: "Knowledge Documents",
    description: "Reference metadata, stored files, categories, previews, and citation relationships.",
  },
  {
    id: "activity",
    label: "Activity Events",
    description: "Workflow history for approvals, assignments, note changes, and document actions.",
  },
];

export const workspaceManualWorkItems: WorkspaceManualWorkItem[] = [
  {
    id: "providers",
    label: "Choose production providers",
    description: "Pick database, auth, file storage, AI, inbox integration, and hosting services.",
  },
  {
    id: "access",
    label: "Create projects and credentials",
    description: "Set up accounts, API keys, environment variables, and deployment access.",
  },
  {
    id: "rules",
    label: "Define workflow rules",
    description: "Decide who can approve, assign, auto-send, and retain activity or document history.",
  },
  {
    id: "data",
    label: "Provide real operating data",
    description: "Supply policy files, real staff roster, email patterns, and category taxonomy.",
  },
];

export const workspaceOperatingDepartments = [
  "Admissions",
  "Finance",
  "Registrar",
  "Academic",
] as const;

export const workspaceWorkflowStages: WorkspaceWorkflowStage[] = [
  {
    id: "created",
    label: "Created",
    description: "A case enters the system from manual intake or future email ingestion.",
  },
  {
    id: "routed",
    label: "Routed",
    description: "The local routing layer suggests a department, owners, and escalation risk.",
  },
  {
    id: "assigned",
    label: "Assigned",
    description: "A staff owner takes responsibility for review and response handling.",
  },
  {
    id: "reviewed",
    label: "Reviewed",
    description: "Drafts, notes, sources, and routing signals are checked by a human.",
  },
  {
    id: "approved",
    label: "Approved or Escalated",
    description: "The case is either approved for send or kept in manual escalation handling.",
  },
];
